// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Epic Digital Interactive Media LLC

import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { extractObservationIds, scanForClaudeMdReferences } from '../claude-md-scanner'

let tempDir: string

beforeEach(() => {
  tempDir = join(tmpdir(), `saga-test-claude-md-${Date.now()}`)
  mkdirSync(tempDir, { recursive: true })
})

afterEach(() => {
  rmSync(tempDir, { recursive: true, force: true })
})

const SAMPLE_CLAUDE_MD = `# Package

<claude-mem-context>
# Recent Activity

<!-- This section is auto-generated by claude-mem. Edit content outside the tags. -->

### Mar 28, 2026

| ID | Time | T | Title | Read |
|----|------|---|-------|------|
| #37080 | 6:40 AM | 🔵 | Found caching pattern | ~487 |
| #37081 | 6:41 AM | ✅ | Session complete | ~1312 |
| #32574 | 2:30 AM | ✅ | Secrets docs updated | ~273 |
</claude-mem-context>

Some other content.
`

const NO_CONTEXT_CLAUDE_MD = `# Package

Just a regular CLAUDE.md with no context block.
`

describe('extractObservationIds', () => {
  it('extracts IDs from a claude-mem-context block', () => {
    const ids = extractObservationIds(SAMPLE_CLAUDE_MD)
    expect(ids).toEqual([37080, 37081, 32574])
  })

  it('returns empty array when no context block exists', () => {
    const ids = extractObservationIds(NO_CONTEXT_CLAUDE_MD)
    expect(ids).toEqual([])
  })

  it('returns empty array for empty string', () => {
    expect(extractObservationIds('')).toEqual([])
  })

  it('handles context block with no table rows', () => {
    const content = `<claude-mem-context>
# Recent Activity

*No recent activity*
</claude-mem-context>`
    expect(extractObservationIds(content)).toEqual([])
  })

  it('handles malformed context block (missing end tag)', () => {
    const content = `<claude-mem-context>
| #12345 | data |`
    expect(extractObservationIds(content)).toEqual([])
  })
})

describe('scanForClaudeMdReferences', () => {
  it('finds CLAUDE.md files with observation references', () => {
    writeFileSync(join(tempDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(1)
    expect(refs[0].filePath).toBe(join(tempDir, 'CLAUDE.md'))
    expect(refs[0].observationIds).toEqual([37080, 37081, 32574])
  })

  it('skips CLAUDE.md files without observation references', () => {
    writeFileSync(join(tempDir, 'CLAUDE.md'), NO_CONTEXT_CLAUDE_MD)

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(0)
  })

  it('recurses into subdirectories', () => {
    const subDir = join(tempDir, 'packages', 'my-pkg')
    mkdirSync(subDir, { recursive: true })
    writeFileSync(join(subDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(1)
    expect(refs[0].filePath).toBe(join(subDir, 'CLAUDE.md'))
  })

  it('skips node_modules directories', () => {
    const nmDir = join(tempDir, 'node_modules', 'some-pkg')
    mkdirSync(nmDir, { recursive: true })
    writeFileSync(join(nmDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(0)
  })

  it('skips .git directories', () => {
    const gitDir = join(tempDir, '.git', 'hooks')
    mkdirSync(gitDir, { recursive: true })
    writeFileSync(join(gitDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(0)
  })

  it('respects maxDepth', () => {
    // Create a deeply nested CLAUDE.md
    const deepDir = join(tempDir, 'a', 'b', 'c', 'd')
    mkdirSync(deepDir, { recursive: true })
    writeFileSync(join(deepDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    // With maxDepth=2, should not reach depth 4
    const refs = scanForClaudeMdReferences(tempDir, 2)
    expect(refs).toHaveLength(0)

    // With default maxDepth (10), should find it
    const refsDeep = scanForClaudeMdReferences(tempDir)
    expect(refsDeep).toHaveLength(1)
  })

  it('returns empty array for nonexistent directory', () => {
    const refs = scanForClaudeMdReferences('/nonexistent/path')
    expect(refs).toHaveLength(0)
  })

  it('finds multiple CLAUDE.md files across a tree', () => {
    writeFileSync(join(tempDir, 'CLAUDE.md'), SAMPLE_CLAUDE_MD)

    const pkgDir = join(tempDir, 'packages', 'cli')
    mkdirSync(pkgDir, { recursive: true })
    writeFileSync(
      join(pkgDir, 'CLAUDE.md'),
      `<claude-mem-context>
| ID | Time | T | Title | Read |
|----|------|---|-------|------|
| #99999 | 1:00 PM | 🔵 | CLI setup | ~100 |
</claude-mem-context>`
    )

    const refs = scanForClaudeMdReferences(tempDir)
    expect(refs).toHaveLength(2)

    const allIds = refs.flatMap(r => r.observationIds)
    expect(allIds).toContain(37080)
    expect(allIds).toContain(99999)
  })
})
