// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Epic Digital Interactive Media LLC

export type {
  ExportType,
  ChainId,
  StorageRef,
  PrivacyConfig,
  SignatureEnvelope,
  AutonomyLevel,
  ProfileType,
  TaskStatus,
  TaskOutcome,
  ArtifactType,
  EpisodicEventType,
  ExpertiseLevel,
  ExpertiseEvidence,
  AuthorityLevel,
  PeerRelationship,
  RuntimeType,
  SystemPromptFormat,
  VaultItemType,
  VaultPermission,
  VaultEncryptionAlgorithm,
  VaultKeyDerivation,
  VaultKeyWrapAlgorithm,
  DataClassification,
  RedactionAction,
  RedactableEntryType,
  ExitReason,
  DisputeStatus,
} from './common'

export type {
  IdentityLayer,
  PersonalityConfig,
  PersonaLayer,
  ModelRef,
  CognitiveParameters,
  SystemPrompt,
  CapabilitiesConfig,
  BehaviorFlags,
  CognitiveLayer,
  ShortTermMemory,
  LongTermMemory,
  EpisodicEvent,
  EpisodicMemory,
  ExpertiseEntry,
  SemanticMemory,
  ProceduralWorkflow,
  ProceduralMemory,
  MemoryLayer,
  VerifiedSkill,
  SelfReportedSkill,
  SkillEndorsement,
  SkillCapabilities,
  SkillsLayer,
  TaskHistorySummary,
  RecentTask,
  TaskArtifact,
  TaskHistoryLayer,
  OrganizationRelationship,
  Principal,
  PeerAgent,
  RelationshipsLayer,
  ResourceRequirements,
  RuntimeConfig,
  McpServer,
  ToolsConfig,
  Integration,
  EnvironmentLayer,
  SagaLayers,
  SagaLayerName,
  VaultItemEncryptedPayload,
  VaultKeyWrap,
  VaultItem,
  VaultEncryptionConfig,
  VaultShareGrant,
  VaultLayer,
  VaultLoginFields,
  VaultApiKeyFields,
  VaultOAuthTokenFields,
  VaultSshKeyFields,
  VaultCertificateFields,
  VaultNoteFields,
  VaultDecryptedFields,
  ClassificationMeta,
  RedactionEntry,
  RedactionSummary,
  RedactionManifest,
} from './layers'

export type { SagaDocument, SignedSagaDocument, ConsentMessage } from './saga-document'
export type { PartialSagaDocument } from './partial'

// ── Compliance types (Section 15.5–15.9, 16A) ───────────────────────
export type {
  ConsentOperation,
  ConsentRecord,
  AuditEventType,
  AuditEvent,
  RetentionPolicyEntry,
  DeletionStatus,
  DeletionScope,
  DeletionRequest,
  RetentionException,
  BreachSeverity,
  BreachNotification,
  ProcessingRole,
  SubProcessorRecord,
  ServerComplianceMetadata,
} from './compliance'
